### PR TITLE
fix: select with alias

### LINKED ISSUE #93: Has column alias in rel.Select
I like the `Select` way for writing queries, it provides a good DSL, so I use it to write a semi-complex query instead of the `SQL` function.

But it seems it doesn't handle the column alias properly:

https://github.com/Fs02/rel/blob/3af9e733867dc779d166d97e05a6cc91b369cd13/adapter/sql/util.go#L27

My code looks like:
```
query := Select(col+"col", "round((count(*)::float / (select count(*) / 100 from apartments))::numeric, 0) ratio").
.....
```

And generate SQL is:
```
SELECT "beds as col",roun .....
```

So is there a chance you make the `Escape` function alias-aware?

### PR DESCRIPTION
**Pull request by h4ckm03d**
Fix #93

### CODE REVIEW

File: adapter/sql/util.go [hunk 1]
```diff
@@ -23,12 +23,21 @@ type fieldCacheKey struct {
...
+	alias  string
+}
+
 // Escape field or table name.
 func Escape(config Config, field string) string {
 	if config.EscapeChar == "" || field == "*" {
 		return field
 	}
 
+	if v, ok := isAliasField(field); ok {
```
Comment (Fs02) [inline adapter/sql/util.go:37]: I think we should cache the result as well by moving this to line 46

Comment (h4ckm03d) [reply adapter/sql/util.go:37]: That's ok, will update soon

File: adapter/sql/util.go [hunk 2]
```diff
@@ -51,6 +63,19 @@ func Escape(config Config, field string) string {
 	return escapedField.(string)
 }
 
+func isAliasField(field string) (*aliasField, bool) {
+	if !strings.Contains(strings.ToLower(field), " as ") {
+		return nil, false
+	}
+
+	f := strings.Fields(field)
```
Comment (Fs02) [inline adapter/sql/util.go:71]: I think we can just use Index (https://golang.org/pkg/strings/#Index) function, and then split and merge the string manually using the returned index, that way the lookup inside string only happened once, not twice (Contains, Fields)

File: adapter/sql/util_test.go [hunk 3]
```diff
@@ -28,3 +28,53 @@ func TestToInt64(t *testing.T) {
...
+			field:  "count(*) as count",
+			result: "count(*) AS count",
+		},
+		{
+			field:  "count(*) as count", // duplicated test to simulate cache load
+			result: "count(*) AS count",
+		},
+		{
+			field:  "user.address as home_address",
+			result: "`user`.`address` AS home_address",
```
Comment (Fs02) [inline adapter/sql/util_test.go:52]: `home_address` need to be escaped as well since it's a field, and user may use reserved keyword as their alias

File: adapter/sql/util.go [hunk 4]
```diff
@@ -35,6 +40,13 @@ func Escape(config Config, field string) string {
 		return escapedField.(string)
 	}
 
+	if v, ok := isAliasField(field); ok {
+		aliasField := Escape(config, v.source) + " AS " + v.alias
```
Comment (Fs02) [inline adapter/sql/util.go:44]: just follow the pattern and assign the result to `escapedField`? that way we can limit three return statement in this function (which is limited to 4 by codeclimate)

Comment (Fs02) [reply adapter/sql/util.go:44]: also the, it might be better if statement below can be refactored using switch, I think it's more readable

File: adapter/sql/util.go [hunk 5]
```diff
@@ -51,6 +63,19 @@ func Escape(config Config, field string) string {
 	return escapedField.(string)
 }
 
+func isAliasField(field string) (*aliasField, bool) {
```
Comment (Fs02) [inline adapter/sql/util.go:66]: I think this function can be simplified or even put inline the escape function.

if we decide to keep it, maybe `escapeAliasField` is better name, since it's also return value, not only boolean.
also I think it's better to return 3 variable instead of aliasField struct.

a bit about returning pointer, I think we should avoid it whenever possible, because:
- non pointer value is easier to analyze by escape analysis, and it's as fast or more faster than pointer value from mini benchmark I've tried
- no need to handle null pointer

File: adapter/sql/util.go [hunk 6]
```diff
@@ -51,6 +63,19 @@ func Escape(config Config, field string) string {
...
+	if !strings.Contains(strings.ToLower(field), " as ") {
+		return nil, false
+	}
+
+	f := strings.Fields(field)
+	if len(f) != 3 {
```
Comment (Fs02) [inline adapter/sql/util.go:72]: if we decide to use index, maybe we can drop this validation an let whatever happens haha
since we only want to know the first ` as ` word that appears inside the select statement, other case will be resulting in query error and need to be handled without auto escaping

File: adapter/sql/util_test.go (hunk 3 above)
Comment (h4ckm03d) [reply adapter/sql/util_test.go:52]: I see so the other unit test need adjust to escape alias field

File: adapter/sql/util_test.go [hunk 7]
```diff
@@ -28,3 +28,57 @@ func TestToInt64(t *testing.T) {
...
+		{
+			field:  "count(*) as count", // duplicated test to simulate cache load
+			result: "count(*) AS `count`",
+		},
+		{
+			field:  "user.address as home_address",
+			result: "`user`.`address` AS `home_address`",
+		},
+		{
+			field:  "^FIELD(`gender`, \"male\") AS order",
```
Comment (Fs02) [inline adapter/sql/util_test.go:59]: This behavior shouldn't be changed, when using `^` as the first character, the field should not be escaped

**Review by Fs02 — APPROVED** [review]
